package com.royalankit.zoya.ui

import android.Manifest
import android.app.Activity
import android.content.*
import android.content.pm.PackageManager
import android.graphics.Color
import android.media.projection.MediaProjectionManager
import android.os.*
import android.provider.Settings
import android.app.role.RoleManager
import android.view.*
import android.widget.*
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AlertDialog
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.firestore.FirebaseFirestore
import com.royalankit.zoya.R
import com.royalankit.zoya.ai.GeminiClient
import com.royalankit.zoya.auth.FirebaseAuthManager
import com.royalankit.zoya.commands.ActionExecutor
import com.royalankit.zoya.core.Capability
import com.royalankit.zoya.core.DeveloperProfile
import com.royalankit.zoya.core.SecureStore
import com.royalankit.zoya.memory.CloudHistory
import com.royalankit.zoya.memory.HistoryStore
import com.royalankit.zoya.permissions.PermissionManager
import com.royalankit.zoya.service.ScreenCaptureManager
import com.royalankit.zoya.service.ZoyaVoiceService
import java.util.Date

class MainActivity:AppCompatActivity(){
    private lateinit var authManager:FirebaseAuthManager;private lateinit var secure:SecureStore;private lateinit var history:HistoryStore;private lateinit var cloud:CloudHistory;private val gemini=GeminiClient();private var screenProjection:android.media.projection.MediaProjection?=null;private lateinit var screenCapture:ScreenCaptureManager
    private lateinit var root:LinearLayout;private lateinit var state:TextView;private lateinit var caption:TextView;private var uid:String?=null
    private val googleLauncher=registerForActivityResult(ActivityResultContracts.StartActivityForResult()){r->if(r.resultCode==Activity.RESULT_OK){try{val account=GoogleSignIn.getSignedInAccountFromIntent(r.data).result;if(account.idToken!=null)authManager.signInWithGoogleToken(account.idToken!!){ok,err->runOnUiThread{if(ok)onLoggedIn()else toast(err?:"Google login failed")}}else toast("Google account token missing")}catch(e:Exception){toast(e.message?:"Google login failed")}}}
    private val permLauncher=registerForActivityResult(ActivityResultContracts.RequestMultiplePermissions()){showPermissions()}
    private val screenLauncher=registerForActivityResult(ActivityResultContracts.StartActivityForResult()){r->if(r.resultCode==RESULT_OK&&r.data!=null){screenProjection=getSystemService(MediaProjectionManager::class.java).getMediaProjection(r.resultCode,r.data!!);captureScreen()}else toast("Screen capture consent नहीं मिला।")}
    private val cameraLauncher=registerForActivityResult(ActivityResultContracts.TakePicturePreview()){bmp->if(bmp==null){toast("Camera image नहीं मिली।");return@registerForActivityResult};val u=uid?:return@registerForActivityResult;val key=secure.getApiKey(u);if(key.isNullOrBlank()){toast("पहले Gemini API key save करें।");return@registerForActivityResult};val model=secure.getModel(u).orEmpty();if(model.isBlank()){toast("पहले कोई Gemini model auto-detect होने दें।");return@registerForActivityResult};val out=java.io.ByteArrayOutputStream();bmp.compress(android.graphics.Bitmap.CompressFormat.JPEG,80,out);gemini.generateVision(key,model,out.toByteArray(),"Describe this camera image for the user in concise Hindi/Hinglish."){text,err->runOnUiThread{toast(text?:err?:"Vision failed")}}}
    private val receiver=object:BroadcastReceiver(){override fun onReceive(c:Context?,i:Intent?){if(i?.action!=ZoyaVoiceService.ACTION_STATE)return;state.text=i.getStringExtra(ZoyaVoiceService.EXTRA_STATE).orEmpty().uppercase();caption.text=i.getStringExtra(ZoyaVoiceService.EXTRA_TEXT).orEmpty()}}

    override fun onCreate(b:Bundle?){super.onCreate(b);window.statusBarColor=Color.rgb(7,7,9);authManager=FirebaseAuthManager(this);secure=SecureStore(this);history=HistoryStore(this);cloud=CloudHistory();screenCapture=ScreenCaptureManager(this);uid=authManager.currentUser()?.uid;if(uid==null)showLogin()else onLoggedIn()}
    override fun onStart(){super.onStart();ContextCompat.registerReceiver(this,receiver,IntentFilter(ZoyaVoiceService.ACTION_STATE),ContextCompat.RECEIVER_NOT_EXPORTED)}
    override fun onStop(){unregisterReceiver(receiver);super.onStop()}
    private fun base():LinearLayout=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(22,18,22,18);setBackgroundColor(Color.rgb(7,7,9))}
    private fun text(t:String,size:Float=16f)=TextView(this).apply{text=t;textSize=size;setTextColor(Color.WHITE);setPadding(4,4,4,4)}
    private fun button(t:String)=Button(this).apply{text=t;isAllCaps=false;setTextColor(Color.WHITE);setBackgroundColor(Color.rgb(25,28,40));setPadding(18,12,18,12)}
    private fun showLogin(){root=base();val spacer=Space(this);root.addView(spacer,LinearLayout.LayoutParams(1,0,1f));val frame=RoyalOrbitalView(this);root.addView(frame,LinearLayout.LayoutParams(-1,18));val card=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,28,24,28);setBackgroundColor(Color.rgb(18,19,26));gravity=Gravity.CENTER_HORIZONTAL};val logo=ImageView(this).apply{setImageResource(R.drawable.royal_logo);scaleType=ImageView.ScaleType.CENTER_CROP};card.addView(logo,LinearLayout.LayoutParams(118,118));card.addView(text("ZOYA AI VOICE ASSISTANT",22f));card.addView(text("By Royal Ankit Ahiran",13f));val info=text("Personal Android AI assistant\nVoice • Chat • Memory • Automation",14f);info.gravity=Gravity.CENTER;card.addView(info);val google=button("Continue with Google");google.setOnClickListener{val client=authManager.googleClient(this);if(client==null){toast("Firebase/Google configuration missing. Set the build properties shown in README.")}else googleLauncher.launch(client.signInIntent)};card.addView(google,LinearLayout.LayoutParams(-1,58).apply{topMargin=22});root.addView(card,LinearLayout.LayoutParams(-1,-2));root.addView(spacer,LinearLayout.LayoutParams(1,0,1f));setContentView(root)}
    private fun onLoggedIn(){uid=authManager.currentUser()?.uid;cloud.syncRecent(uid!!,history);showMain()}
    private fun showMain(){root=base();val top=LinearLayout(this);val dev=button("⋮");val profile=button("Profile");top.addView(dev,LinearLayout.LayoutParams(0,56,1f));top.addView(profile,LinearLayout.LayoutParams(0,56,1f));root.addView(top);dev.setOnClickListener{developer()};profile.setOnClickListener{profile()};val orbital=FrameLayout(this);orbital.addView(RoyalOrbitalView(this),FrameLayout.LayoutParams(-1,-1));val logo=ImageView(this).apply{setImageResource(R.drawable.royal_logo);scaleType=ImageView.ScaleType.CENTER_INSIDE};orbital.addView(logo,FrameLayout.LayoutParams(-1,-1));root.addView(orbital,LinearLayout.LayoutParams(-1,0,1f));state=text("READY",12f);state.gravity=Gravity.CENTER;caption=text("Say “Zoya” to begin",20f);caption.gravity=Gravity.CENTER;caption.setOnClickListener{textChat()};root.addView(state);root.addView(caption,LinearLayout.LayoutParams(-1,0,2f));val bottom=LinearLayout(this);val mic=button("🎙  Microphone");val share=button("▣  Screen Share");bottom.addView(mic,LinearLayout.LayoutParams(0,60,1f));bottom.addView(share,LinearLayout.LayoutParams(0,60,1f));root.addView(bottom);mic.setOnClickListener{startVoice()};share.setOnClickListener{requestScreen()};setContentView(root)}
    private fun startVoice(){if(ContextCompat.checkSelfPermission(this,Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){permLauncher.launch(arrayOf(Manifest.permission.RECORD_AUDIO,Manifest.permission.POST_NOTIFICATIONS));return};ContextCompat.startForegroundService(this,Intent(this,ZoyaVoiceService::class.java).setAction(ZoyaVoiceService.ACTION_START));toast("Zoya background voice active")}
    private fun requestScreen(){val m=getSystemService(MediaProjectionManager::class.java);screenLauncher.launch(m.createScreenCaptureIntent())}
    private fun captureScreen(){val p=screenProjection?:return;val u=uid?:return;val key=secure.getApiKey(u);if(key.isNullOrBlank()){toast("Gemini API key save करें।");return};val model=secure.getModel(u).orEmpty();if(model.isBlank()){toast("Model auto-detect नहीं हुआ। पहले Gemini API key validate करें।");return};screenCapture.capture(p){bytes->if(bytes==null){runOnUiThread{toast("Screen frame नहीं मिला")};return@capture};gemini.generateVision(key,model,bytes,"Look at this Android screen and explain what is visible. If there is a clear user-actionable UI, describe it. Do not claim to click anything."){t,e->runOnUiThread{toast(t?:e?:"Vision failed")}}}}
    private fun profile(){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12,4,12,4)};val u=authManager.currentUser()!!;box.addView(text("${u.displayName?:"User"}\n${u.email?:""}\nUID: ${u.uid}",14f));listOf("JARVIS Allow Permission","Language","Gemini API","Hey Zoya","Chat History","Voice History","Memory Search","Master Safety Switch","Activity Log","Logout").forEach{label->val b=button(label);box.addView(b);b.setOnClickListener{when(label){"JARVIS Allow Permission"->showPermissions();"Language"->language();"Gemini API"->geminiKey();"Hey Zoya"->heyZoya();"Chat History"->history(false);"Voice History"->history(true);"Memory Search"->memorySearch();"Master Safety Switch"->safety();"Activity Log"->activityLog();"Logout"->{authManager.signOut();stopService(Intent(this,ZoyaVoiceService::class.java));showLogin()}}}};AlertDialog.Builder(this).setTitle("Zoya Profile").setView(box).setPositiveButton("Close",null).show()}
    private fun language(){val choices=arrayOf("Hindi","English","Bhojpuri","Magahi");AlertDialog.Builder(this).setTitle("Language").setItems(choices){_,w->getSharedPreferences("zoya_user",0).edit().putString("language",choices[w]).apply();toast("Language: ${choices[w]}")}.show()}
    private fun geminiKey(){val u=uid?:return;val input=EditText(this);input.hint="Gemini API key";input.inputType=129;val current=secure.getApiKey(u);input.setText("");val detected=text("Saved: ${if(current.isNullOrBlank())"No" else "Yes"}",13f);val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12,4,12,4);addView(input);addView(detected)};AlertDialog.Builder(this).setTitle("Gemini API").setView(box).setPositiveButton("Save"){_,_->val k=input.text.toString().trim();if(k.isBlank()){toast("Key खाली है");return@setPositiveButton};if(!secure.putApiKey(u,k)){toast("API key format invalid या save नहीं हो पाई");return@setPositiveButton};secure.removeModel(u);gemini.listModels(k){models,err->val best=models.filter{it.methods.any{m->m.contains("generateContent")}}.sortedBy{if(it.name.contains("flash",true))0 else 1}.firstOrNull();runOnUiThread{if(best!=null){secure.putModel(u,best.name);toast("Model detected: ${best.name}")}else toast(err?:"No compatible model found")}}}.setNeutralButton("Remove"){_,_->secure.removeApiKey(u);secure.removeModel(u)}.setNegativeButton("Close",null).show()}
    private fun heyZoya(){if(Build.VERSION.SDK_INT>=29){try{val rm=getSystemService(RoleManager::class.java);if(rm.isRoleAvailable(RoleManager.ROLE_ASSISTANT)&&!rm.isRoleHeld(RoleManager.ROLE_ASSISTANT))startActivity(rm.createRequestRoleIntent(RoleManager.ROLE_ASSISTANT))else toast("Zoya Assistant role already active या device पर उपलब्ध नहीं है।")}catch(_:Exception){startActivity(Intent(Settings.ACTION_VOICE_INPUT_SETTINGS))}}else startActivity(Intent(Settings.ACTION_VOICE_INPUT_SETTINGS))}
    private fun showPermissions(){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12,0,12,0)};Capability.entries.forEach{c->val row=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val label=text("${c.title}\n${c.purpose}",13f);row.addView(label,LinearLayout.LayoutParams(0,-2,1f));val b=button(status(c));row.addView(b);b.setOnClickListener{grant(c);};box.addView(row)};AlertDialog.Builder(this).setTitle("Zoya Allow Permission").setMessage("हर capability का अलग Android access है। केवल वही access माँगा जाएगा जो feature को चाहिए।").setView(ScrollView(this).apply{addView(box)}).setPositiveButton("Close",null).show()}
    private fun status(c:Capability)=when(c.special){com.royalankit.zoya.core.Special.ACCESSIBILITY->if(PermissionManager.accessibility(this))"ON" else "OPEN";com.royalankit.zoya.core.Special.NOTIFICATION_LISTENER->if(PermissionManager.notifications(this))"ON" else "OPEN";else->if(c.permission==null)"INFO" else if(ContextCompat.checkSelfPermission(this,c.permission)==PackageManager.PERMISSION_GRANTED)"ON" else "GRANT"}
    private fun grant(c:Capability){when(c.special){com.royalankit.zoya.core.Special.ACCESSIBILITY->startActivity(PermissionManager.accessibilitySettings());com.royalankit.zoya.core.Special.NOTIFICATION_LISTENER->startActivity(PermissionManager.notificationSettings());com.royalankit.zoya.core.Special.ASSISTANT->heyZoya();com.royalankit.zoya.core.Special.MEDIA_PROJECTION->requestScreen();com.royalankit.zoya.core.Special.UNSUPPORTED_ADMIN->toast("Device Admin is not enabled automatically; Android policy controls this.");else->c.permission?.let{if(it==Manifest.permission.POST_NOTIFICATIONS&&Build.VERSION.SDK_INT<33)return;permLauncher.launch(arrayOf(it))}}
    }
    private fun developer(){AlertDialog.Builder(this).setTitle("Developer").setMessage("${DeveloperProfile.NAME}\n\nInstagram\n${DeveloperProfile.INSTAGRAM}\n\nFacebook\n${DeveloperProfile.FACEBOOK}\n\nTelegram\n${DeveloperProfile.TELEGRAM}\n\nYouTube\n${DeveloperProfile.YOUTUBE}\n\nWhatsApp\n${DeveloperProfile.WHATSAPP}\n\nEmail\n${DeveloperProfile.EMAIL}\n\nWebsite / Portfolio\n${DeveloperProfile.WEBSITE}\n\nZoya AI Voice Assistant\n${DeveloperProfile.ZOYA_LINK}").setPositiveButton("Close",null).show()}
    private fun history(voice:Boolean){val u=uid?:return;val items=history.recent(u,100).filter{if(voice)it.kind=="voice" else it.kind=="chat"};val body=items.joinToString("\n\n"){ "${java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",java.util.Locale.US).format(Date(it.ts))}\nUSER: ${it.user}\nZOYA: ${it.assistant}"}.ifBlank{"No history found."};AlertDialog.Builder(this).setTitle(if(voice)"Voice History" else "Chat History").setMessage(body).setPositiveButton("Close",null).show()}
    private fun memorySearch(){val input=EditText(this);input.hint="Topic, person, place or date";AlertDialog.Builder(this).setTitle("Search old memory").setView(input).setPositiveButton("Search"){_,_->val u=uid?:return@setPositiveButton;val q=input.text.toString();val found=history.search(u,q,20);val body=found.joinToString("\n\n"){ "${java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",java.util.Locale.US).format(Date(it.ts))}\n${it.user}\n${it.assistant}"}.ifBlank{"इस topic का saved record नहीं मिला। शायद history delete हो चुकी है या कभी save नहीं हुई।"};AlertDialog.Builder(this).setTitle("Memory Results").setMessage(body).setPositiveButton("Close",null).show()}.setNegativeButton("Close",null).show()}
    private fun safety(){val p=getSharedPreferences("zoya_safety",0);val on=p.getBoolean("enabled",true);p.edit().putBoolean("enabled",!on).apply();toast("Master Safety Switch: ${if(on)"OFF" else "ON"}")}
    private fun activityLog(){val u=uid?:return;val body=history.recent(u,100).joinToString("\n\n"){ "${java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",java.util.Locale.US).format(Date(it.ts))} [${it.kind}]\n${it.user}\n→ ${it.assistant}"}.ifBlank{"No activity yet."};AlertDialog.Builder(this).setTitle("Activity Log").setMessage(body).setPositiveButton("Close",null).show()}
    private fun textChat(){val input=EditText(this);input.hint="Talk to Zoya…";AlertDialog.Builder(this).setTitle("Zoya Chat").setView(input).setPositiveButton("Send"){_,_->val u=uid?:return@setPositiveButton;val key=secure.getApiKey(u);if(key.isNullOrBlank()){toast("Gemini API key save करें");return@setPositiveButton};val model=secure.getModel(u).orEmpty();if(model.isBlank()){toast("API key validate करें");return@setPositiveButton};val q=input.text.toString();gemini.generate(key,model,q,history.memoryContext(u,q)){r,e->runOnUiThread{if(r==null)toast(e?:"Gemini failed")else{history.add(u,"chat",q,r.text);cloud.save(u,"chat",q,r.text);AlertDialog.Builder(this).setTitle("Zoya").setMessage(r.text).setPositiveButton("Close",null).show()}}}}.setNegativeButton("Close",null).show()}
    private fun toast(s:String){Toast.makeText(this,s,Toast.LENGTH_LONG).show()}
    override fun onDestroy(){screenCapture.cleanup();super.onDestroy()}
}
